# swiftlint.yml

included:
  - WeatherApp
  - WeatherAppTests

excluded:
  - Pods
  - Carthage
  - Generated
  - .build
  - DerivedData

analyzer_rules:
  - unused_import

opt_in_rules:
  - closure_spacing
  - empty_count
  - force_unwrapping
  - implicit_getter
  - vertical_parameter_alignment
  - explicit_init
  - redundant_nil_coalescing
  - identifier_name
  - discouraged_direct_init
  - multiline_function_chains

disabled_rules:
  - trailing_whitespace
  - todo # handled manually with custom_rules

# Length limits
function_body_length:
  warning: 40
  error: 75

type_body_length:
  warning: 200
  error: 350

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# Custom rules for comments
custom_rules:
  mark_usage:
    included: ".*\\.swift"
    name: "MARK Usage"
    regex: "^(?!.*//\\s?MARK:).*(func\\s|class\\s|struct\\s|enum\\s)"
    message: "Use // MARK: to organize code sections."
    severity: warning
    match_kinds:
      - source.lang.swift.decl.class
      - source.lang.swift.decl.struct
      - source.lang.swift.decl.enum
      - source.lang.swift.decl.function.free
      - source.lang.swift.decl.function.method.instance
      - source.lang.swift.decl.function.method.static
    excluded:
      - ".*Tests\\.swift$"
      - ".*Mock\\.swift$"

  fixme_todo_format:
    included: ".*\\.swift"
    name: "TODO / FIXME Format"
    regex: ".*(TODO|FIXME)[^:]"
    message: "TODO or FIXME should be followed by a colon (`TODO:`)."
    severity: warning

  doc_comment_required:
    included: ".*\\.swift"
    name: "Doc Comment Required"
    regex: "^\\s*(public|open)\\s+(class|func|var|let|struct|enum)\\b(?![^\\n]*///)"
    message: "Public declarations should be documented using triple-slash `///` comments."
    severity: warning
